name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: "0 2 * * 1-5"  # run on weekdays at 2:00am UTC

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Setup mamba
      uses: goanpeca/setup-miniconda@v1
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Create the conda environment
      shell: bash -l {0}
      run: mamba install -q python=${{ matrix.python-version }} pip jupyterlab_pygments==0.1.0 pytest-cov nodejs flake8 ipywidgets matplotlib xeus-cling

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        whereis python
        python --version

        python -m pip install ".[test]"
        cd tests/test_template; pip install .; cd ../../;

    - name: Flake8
      shell: bash -l {0}
      run: |
        python -m flake8 voila tests setup.py

    - name: Run tests
      shell: bash -l {0}
      run: |
        VOILA_TEST_DEBUG=1 VOILA_TEST_XEUS_CLING=1 py.test tests/ --async-test-timeout=240
        voila --help  # Making sure we can run `voila --help`
